version: "3.8"
name: th-monolith_dev

services:
  api:
    build:
      context: talent-hub-api
      dockerfile: dev.Dockerfile
    ports:
      - "5000:5106"
    restart: unless-stopped
    volumes:
      - ./talent-hub-api:/app
    networks:
      - th-dev_net

  bot:
    build:
      context: talent-hub-aleks_bot
      dockerfile: dev.Dockerfile
    ports:
      - "5001:5107"
    env_file:
      - .env
    volumes:
      - ./talent-hub-aleks_bot:/app
    depends_on:
      - bot_postgres
    networks:
      - th-dev_net

  bot_postgres:
    image: "postgres:13"
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - th-dev_net

  web:
    build:
      context: talent-hub_website
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./talent-hub_website:/app
      - /app/node_modules
    networks:
      - th-dev_net


networks:
  th-dev_net:
    driver: bridge