version: "3.8"
name: th-monolith_dev

services:
  api:
    image: quarkus/talent-hub_api-jvm
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./talent-hub_api:/app
    depends_on:
      - api_mongo
      - api_rabbitmq
    networks:
      - th-dev_net

  api_mongo:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    volumes:
      - ./api_mongo:/data/db
    networks:
      - th-dev_net

  api_rabbitmq:
    image: "rabbitmq:3.8-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - th-dev_net

  bot:
    build:
      context: talent-hub-aleks_bot
      dockerfile: dev.Dockerfile
    ports:
      - "5001:5107"
    env_file:
      - .env
    volumes:
      - ./talent-hub-aleks_bot:/app
    depends_on:
      - bot_postgres
    networks:
      - th-dev_net

  bot_postgres:
    image: "postgres:13"
    env_file:
      - .env
    ports:
      - "5439:5432"
    volumes:
      - ./bot_postgres:/var/lib/postgresql/data
    networks:
      - th-dev_net

networks:
  th-dev_net:
    driver: bridge
