version: "3.8"
name: th-monolith_dev

services:
  api:
    build:
      context: talent-hub_api
      dockerfile: src/main/docker/Dockerfile.dev
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./talent-hub_api:/app
    networks:
      - th-dev_net

  bot:
    build:
      context: talent-hub-aleks_bot
      dockerfile: dev.Dockerfile
    ports:
      - "5001:5107"
    env_file:
      - .env
    volumes:
      - ./talent-hub-aleks_bot:/app
    depends_on:
      - bot_postgres
    networks:
      - th-dev_net

  bot_postgres:
    image: "postgres:13"
    env_file:
      - .env
    ports:
      - "5439:5432"
    volumes:
      - ./bot_postgres:/var/lib/postgresql/data
    networks:
      - th-dev_net

networks:
  th-dev_net:
    driver: bridge
